CREATE TABLE books_catalogue (
    titolo VARCHAR(40) not null,
    autore VARCHAR(40) not null,
    prezzo VARCHAR(10) not null,
    data_rilascio VARCHAR(20) not null,
    descrizione VARCHAR(1000000) not null,
    isbn VARCHAR(13) not null,
    img VARCHAR(10000) not null 
);

INSERT INTO books_catalogue VALUES ('Crime', 'Irvine Welsh', '18,05 €', '7 aprile 2022', 'Sotto la luce impietosa del sole della Florida, Irvine Welsh scandaglia le profondità più innominabili della crudeltà e del rimorso umano, con la sua penna sempre tagliente e anfetaminica.', '9788823530461', 'https://www.lafeltrinelli.it/images/9788823530461_0_536_0_75.jpg');

INSERT INTO books_catalogue VALUES ('La stanza delle mele', 'Matteo Righetto', '17,10 €', '7 aprile 2022', 'Matteo Righetto conosce profondamente il mondo arcaico della montagna – durissimo e al contempo vivo di profumi, sapori, dialetto e leggende – e ce lo restituisce nel suo romanzo più maturo e incalzante. Leggerlo è una corsa notturna nel bosco, con il cuore in gola.', '9788807034909', 'https://www.lafeltrinelli.it/images/9788807034909_0_536_0_75.jpg');

INSERT INTO books_catalogue VALUES ('Stalingrado', 'Vasilij Grossman', '26,60 €', '4 aprile 2022', 'Uno dei più grandi romanzi del Novecento – dove i «fatti del mondo e il destino delle persone diventano tutt uno».', '9788845936517', 'https://www.lafeltrinelli.it/images/9788845936517_0_536_0_75.jpg');

INSERT INTO books_catalogue VALUES ('Jova Beach Coloring', 'Jovanotti', '9,40 €', '7 aprile 2022', 'Jova Beach Party è un grande gioco, dove ognuno mette del suo e le linee creano campi da colorare, attraversare, far vivere. Divertitevi a remixare, immaginare, fantasticare.', '9788807493225', 'https://www.lafeltrinelli.it/images/9788807493225_0_536_0_75.jpg');

INSERT INTO books_catalogue VALUES ('Così per sempre', 'Chiara Valerio', '20,90 €', '5 aprile 2022', 'L uomo sulla terrazza è antico quasi come la città che sta guardando. Il suo gatto Zibetto, piú nero di tutti i gatti neri, come lui conosce troppe storie. L uomo è il conte Dracula. Ama la scienza, la fragilità degli esseri umani, e una donna dal viso sempre uguale.', '9788806252564', 'https://www.lafeltrinelli.it/images/9788806252564_0_536_0_75.jpg');

INSERT INTO books_catalogue VALUES ('Quindici riprese', 'Walter Siti', '19,00 €', '5 aprile 2022', 'In questo volume Siti raccoglie finalmente tutti i suoi saggi pasoliniani, dal 1972 a oggi, con scritti ad ampio raggio e altri più specifici o occasionali. Un interpretazione originale e che matura progressivamente di uno dei nostri autori novecenteschi più polemici e discussi, in grado di attrarre, come è stato per Siti, chi voglia riflettere sui rapporti intricati tra letteratura e vita.', '9788817083065', 'https://www.lafeltrinelli.it/images/9788817083065_0_536_0_75.jpg');

INSERT INTO books_catalogue VALUES ('Credere', 'Julián Carrón', '16,06 €', '5 aprile 2022', 'Una delle personalità cattoliche più interessanti del panorama attuale dialoga con uno dei filosofi e psicanalisti più conosciuti in Italia sul senso profondo della parola credere. Ne scaturisce un confronto di altissimo livello e allo stesso tempo chiaro e illuminante, ricco di suggestioni e possibili declinazioni.', '9788856685022', 'https://www.lafeltrinelli.it/images/9788856685022_0_536_0_75.jpg');

INSERT INTO books_catalogue VALUES ('Lontani parenti', 'Veit Heinichen', '17,10 €', '6 aprile 2022', 'Due uomini uccisi nel giro di poche ore, entrambi con una freccia tirata da una balestra professionale, ovviamente fanno pensare alla stessa mano. Ma quando gli omicidi vengono collegati ad altri avvenuti negli ultimi mesi in zone più o meno limitrofe, il caso si inserisce in un contesto politico e la prospettiva cambia.', '9788833574486', 'https://www.lafeltrinelli.it/images/9788833574486_0_536_0_75.jpg');

INSERT INTO books_catalogue VALUES ('La guerra dei trent anni', 'Filippo Facci', '23,75 €', '7 aprile 2022', 'Cosa fu realmente Mani Pulite? Una rivoluzione giudiziaria o una guerra civile tra i poteri dello Stato? Cambiò davvero tutto o fu soltanto una stagione di illusioni perdute? Una ricostruzione dello scandalo che travolse la scena politica. Una testimonianza d eccezione tra narrazione storica e racconto privato.', '9788829713721', 'https://www.lafeltrinelli.it/images/9788829713721_0_536_0_75.jpg');

INSERT INTO books_catalogue VALUES ('La strategia dell opossum', 'Roberto Alajmo', '13,30 €', '7 aprile 2022', 'La seconda avventura di Giovanni Di Dio, detto Giovà, lo sprovveduto metronotte, investigatore controvoglia, che si colloca a metà tra il siciliano descritto da Giuseppe Tomasi di Lampedusa, che aspira solamente al sonno, e il candido Giufà della tradizione popolare.', '9788838943478', 'https://www.lafeltrinelli.it/images/9788838943478_0_536_0_75.jpg');

INSERT INTO books_catalogue VALUES ('De arte gymnastica', 'Andrea Marcolongo', '15,20 €', '7 aprile 2022', 'E se provassimo per una volta a "correre come correvano i Greci"? Amanti del running oppure no, una cosa è certa. Tutto è cambiato dall epoca di Filippide a oggi – la tecnologia, la politica, la scienza, la guerra, il modo di scrivere, di mangiare, di viaggiare, persino il clima –, ma due cose sono rimaste invariate: i nostri muscoli e quei maledettissimi 41,8 km che separano Maratona dall acropoli di Atene. Proprio quelli che ho intenzione di correre.', '9788858147481', 'https://www.lafeltrinelli.it/images/9788858147481_0_536_0_75.jpg');

INSERT INTO books_catalogue VALUES ('Rancore', 'Gianrico Carofiglio', '17,58 €', '29 marzo 2022', 'Come è morto, davvero, Vittorio Leonardi? Perché Penelope Spada ha dovuto lasciare la magistratura? Un investigazione su un delitto e nei meandri della coscienza. Un folgorante romanzo sulla colpa e sulla redenzione.', '9788806252410', 'https://www.lafeltrinelli.it/images/9788806252410_0_536_0_75.jpg');

INSERT INTO books_catalogue VALUES ('Fabbricante di lacrime', 'Erin Doom', '15,10 €', '27 maggio 2021', 'Il desiderio di una famiglia, un amore impossibile, una sola certezza: non puoi mentire al Fabbricante di lacrime.', '9791259570277', 'https://www.lafeltrinelli.it/images/9791259570277_0_536_0_75.jpg');

INSERT INTO books_catalogue VALUES ('La casa di cielo e aria. Crescent City', 'Sarah J. Maas', '21,76 €', '12 aprile 2022', 'In La casa di cielo e aria, secondo romanzo ricco d azione della nuova serie fantasy Crescent City, dopo La casa di terra e sangue, Sarah J. Maas dà ulteriore prova delle sue capacità di intessere l affascinante storia di un mondo sull orlo del baratro, celebrando il coraggio di coloro che faranno di tutto per salvarlo.', '9788804749325', 'https://www.lafeltrinelli.it/images/9788804749325_0_536_0_75.jpg');

INSERT INTO books_catalogue VALUES ('La mascella di Caino', 'Torquemada', '17,10 €', '8 marzo 2022', 'Sei assassini e sei vittime: chi ha ucciso chi? Il puzzle letterario più diabolico del mondo. Un piccolo gioiello di enigmistica.', '9788804752677', 'https://www.lafeltrinelli.it/images/9788804752677_0_536_0_75.jpg');

INSERT INTO books_catalogue VALUES ('La proposta di un gentiluomo', 'Julia Quinn', '13,78 €', '29 gennaio 2021', 'Sophie Beckett discende da una nobilissima famiglia, ma non ha mai avuto una vita facile. Niente feste, coccole, agi per lei: è infatti la figlia illegittima del conte di Penwood ed è sempre stata trattata come una domestica, soprattutto dopo che il padre, morendo, l ha lasciata sola con la matrigna e le sorellastre. ', '9788804724292', 'https://www.lafeltrinelli.it/images/9788804724292_0_536_0_75.jpg');

INSERT INTO books_catalogue VALUES ('Il duca e io. Serie Bridgerton', 'Julia Quinn', '13,78 €', '22 gennaio 2021', 'Londra, 1813. Simon Arthur Henry Fitzranulph Basset, nuovo duca di Hastings ed erede di uno dei titoli più antichi e prestigiosi d Inghilterra, è uno scapolo assai desiderato. A dire il vero, è letteralmente perseguitato da schiere di madri dell alta società che farebbero di tutto pur di combinare un buon matrimonio per le loro fanciulle in età da marito.', '9788804724278', 'https://www.lafeltrinelli.it/images/9788804724278_0_536_0_75.jpg');

INSERT INTO books_catalogue VALUES ('Dimmi cosa vedi tu da lì', 'Guido Maria Brera', '15,68 €', '7 aprile 2022', 'Intrecciando l’autofiction più vertiginosa alla confessione più intima, il racconto appassionato al saggio divulgativo, Guido Maria Brera disegna lo scenario della grande guerra tra modelli economici che attraversa i decenni, ci proietta nel mezzo di una battaglia decisiva, pronuncia parole di riscatto e speranza. E se nell’assedio che oggi ci minaccia fosse proprio la voce di Federico Caffè a suonare le trombe di Gerico?', '9788828207443', 'https://www.lafeltrinelli.it/images/9788828207443_0_536_0_75.jpg');

INSERT INTO books_catalogue VALUES ('La Russia di Putin', 'Anna Politkovskaja', '13,30 €', '25 marzo 2022', '«Siamo solo un mezzo, per lui. Un mezzo per raggiungere il potere personale. Per questo dispone di noi come vuole. Può giocare con noi, se ne ha voglia. Può distruggerci, se lo desidera. Noi non siamo niente. Lui, finito dov’è per puro caso, è il dio e il re che dobbiamo temere e venerare. La Russia ha già avuto governanti di questa risma. Ed è finita in tragedia.', '9788845936920', 'https://www.lafeltrinelli.it/images/9788845936920_0_536_0_75.jpg');