CREATE TABLE USERS (
    NOME VARCHAR NOT NULL,
    COGNOME VARCHAR NOT NULL,
    EMAIL VARCHAR PRIMARY KEY,
    PASSW VARCHAR NOT NULL,
    INDIRIZZO VARCHAR NOT NULL,
    CITTA VARCHAR NOT NULL,
    CAP NUMERIC NOT NULL
);